// <auto-generated />
using CasoPractico2JoseVargas.DatabaseContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CasoPractico2JoseVargas.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231101184727_MigracionTodosProcedimientosAlmacenados")]
    partial class MigracionTodosProcedimientosAlmacenados
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CasoPractico2JoseVargas.Models.ClientesCasoPractico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellidos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cedula")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Edad")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Preferencias")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Clientes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Apellidos = "Vargas",
                            Cedula = "115180942215",
                            Edad = 31,
                            Nombre = "Jose",
                            Preferencias = "Preferencias uno uno uno"
                        },
                        new
                        {
                            Id = 2,
                            Apellidos = "Prado",
                            Cedula = "1168409454",
                            Edad = 26,
                            Nombre = "Jos",
                            Preferencias = "Preferencias dos dos dos"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
